# Generated by Django 5.0.2 on 2024-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="course_images/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
