# Generated by Django 5.0.2 on 2024-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_image_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="course_images/"
            ),
        ),
    ]
