# Generated by Django 5.0.2 on 2024-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_module_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
