# Generated by Django 5.0.2 on 2024-09-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_lesson_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lesson_videos/"),
        ),
    ]
