# Generated by Django 5.1.1 on 2024-11-09 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_assignment_assignmentrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_url",
                    models.URLField(blank=True, max_length=3000, null=True),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.assignment",
                    ),
                ),
            ],
        ),
    ]
