# Generated by Django 5.1.1 on 2024-11-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_assignment_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="submission",
            field=models.CharField(default="Url Link", max_length=3000, null=True),
        ),
    ]
