# Generated by Django 5.1.1 on 2024-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                blank=True, default="Not Yet Graded", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_link",
            field=models.URLField(blank=True, default="not submited"),
        ),
    ]
