# Generated by Django 5.1.1 on 2024-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0019_alter_progress_assignment_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=3000)),
                ("link", models.URLField()),
                ("dateline", models.DateField()),
            ],
        ),
    ]
